---
- name: dotfiles
  hosts: localhost
  connection: localhost
  become: true

  pre_tasks:
    - name: clone dotfiles
      become_user: archbox
      become: true
      ansible.builtin.git: 
        repo: git@github.com/nooneknowspeter/dotfiles.git
        accept_hostkey: true
        dest: ~/dotfiles
        recursive: true
        key_file: ~/.ssh/id_ed25519

  tasks:
    - name: update system | arch
      include_tasks: .anisble/playbooks/test.yml
      when: ansible_facts['os_family'] == "Archlinux"

    - name: update system | debian
      shell: echo "updating system"
      when: ansible_facts['os_family'] == "Debian"

    - name: update system | nixos
      shell: echo "updating system"
      when: ansible_distribution == "NixOS"

    - name: update system | windows
      shell: echo "updating system"
      when: ansible_facts['os_family'] == "Windows"
