---
- name: dotfiles
  hosts: localhost
  connection: localhost
  become: true

  pre_tasks:
    - name: update system | arch
      shell: echo "updating system"
      when: ansible_facts['os_family'] == "Archlinux"

    - name: update system | debian
      shell: echo "updating system"
      when: ansible_facts['os_family'] == "Debian"

    - name: update system | nixos
      shell: echo "updating system"
      when: ansible_distribution == "NixOS"

    - name: update system | windows
      shell: echo "updating system"
      when: ansible_facts['os_family'] == "Windows"

  tasks:
    - name: test1
      shell: echo "hello"
    - name: test2
      shell: echo "another one"
