- name: update system | arch
  become: true
  ansible.builtin.shell: pacman -Syyu --noconfirm
  args:
    chdir: $HOME

- name: install dependencies
  become: true
  ansible.builtin.shell: pacman -S --needed git base-devel
  
- name: clone yay repo
  ansible.builtin.shell: git clone https://aur.archlinux.org/yay.git

- name: change dir
  ansible.builtin.shell: cd yay

- name: build and install yay
  become: true
  ansible.builtin.shell: makepkg -si --noconfirm

- name: message
  ansible.builtin.shell: yay && echo $?
  args:
    chdir: $HOME
