scoop bucket addd extras
scoop install extras/vscode

code -r --install-extension aaron-bond.better-comments 
code -r --install-extension asvetliakov.vscode-neovim 
code -r --install-extension davidanson.vscode-markdownlint
code -r --install-extension docker.docker
code -r --install-extension esbenp.prettier-vscode
code -r --install-extension felixzeller.markdown-oxide
code -r --install-extension github.github-vscode-theme
code -r --install-extension gitpod.gitpod-desktop
code -r --install-extension henrytsz.nvim
code -r --install-extension ms-azuretools.vscode-docker
code -r --install-extension ms-kubernetes-tools.vscode-kubernetes-tools
code -r --install-extension ms-python.debugpy
code -r --install-extension ms-python.python
code -r --install-extension ms-python.vscode-pylance
code -r --install-extension ms-vscode-remote.remote-containers
code -r --install-extension ms-vscode-remote.remote-ssh
code -r --install-extension ms-vscode-remote.remote-ssh-edit
code -r --install-extension ms-vscode-remote.remote-wsl
code -r --install-extension ms-vscode.remote-explorer
code -r --install-extension ms-vscode.remote-server
code -r --install-extension oliverparaskos.fountain-lsp
code -r --install-extension piersdeseilligny.betterfountain
code -r --install-extension redhat.vscode-yaml
code -r --install-extension s-nlf-fh.glassit
code -r --install-extension streetsidesoftware.code-spell-checker
code -r --install-extension sumneko.lua
code -r --install-extension tal7aouy.icons
code -r --install-extension tek256.simple-dark
code -r --install-extension vincesalvino.dark-plus-black 
code -r --install-extension wayou.vscode-todo-highlight 
