" set relativenumber and number
set number relativenumber

" colorscheme
color habamax

" transparent background
hi Normal          ctermfg=252 ctermbg=none

" clipboard
set clipboard=unnamedplus

" better escape
imap jj <Esc>
