---
- name: clone dotfiles
  become_user: "{{ ansible_facts['user_id'] }}"
  become: true
  ansible.builtin.git:
    repo: git@github.com/nooneknowspeter/dotfiles.git
    accept_hostkey: true
    clone: true
    dest: ~/dotfiles
    recursive: true
    key_file: ~/.ssh/id_ed25519
