[keyboard]
bindings = [
  { key = "V", mods = "Control", action = "Paste" },
  { key = "Space", mods = "Control", chars = "\u0000" },
  { key = "Q", mode = "Vi|~Search", action = "ClearSelection" },
  { key = "Q", mode = "Vi|~Search", action = "ToggleViMode" },
]
