- name: enable execution policy
  become: true
  ansible.builtin.shell: Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope CurrentUser

- name: run scoop install script
  become: true
  ansible.builtin.shell: Invoke-RestMethod -Uri https://get.scoop.sh | Invoke-Expression

- name: install ssh server
  ansible.windows.win_powershell:
      script: |
        Add-Capability OpenSSH.Sever

- name: 
  ansible.windows.win_powershell:
    script: |
      Set-Service sshd -StartupType 'Boot'

      if (!(Get-NetFirewallRule -Name "OpenSSH-Server-In-TCP" -ErrorAction SilentlyContinue | Select-Object Name, Enabled)) {
        Write-Output "Firewall Rule 'OpenSSH-Server-In-TCP' does not exist, creating it..."
        New-NetFirewallRule -Name 'OpenSSH-Server-In-TCP' -DisplayName 'OpenSSH Server (sshd)' -Enabled True -Direction Inbound -Protocol TCP -Action Allow -LocalPort 22
      } else {
          Write-Output "Firewall rule 'OpenSSH-Server-In-TCP' has been created and exists."
      }

      Restart-Server sshd

- name: install packages through scoop
  ansible.builtin.include_tasks:
    file: .ansible/playbooks/win32/install_packages.yml
