name: "nixfmt"
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.CICD }}

      - name: nixfmt
        run: |
          nix develop --impure -c treefmt

      - name: push
        uses: github-actions-x/commit@v2.9
        with:
          github-token: ${{ secrets.CICD }}
          commit-message: "style(ci/cd): treefmt"
          name: github-actions[bot]
          email: github-actions[bot]@users.noreply.github.com
